version: '3.8'

services:

  mysql:
    image: mysql:8.0
    container_name: canil-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: canil_db
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev123
    ports:
      - "3306:3306"
    volumes:
      - canil-mysql-data:/var/lib/mysql

volumes:
  canil-mysql-data: